# Generated by Django 5.1.1 on 2024-09-16 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['updated', 'created']},
        ),
    ]
